/**
 * Demo tours for seed/demo-tours.cjs. Prices, dates and group sizes are illustrative.
 *
 * Photos are Unsplash photo ids (the path part of images.unsplash.com URLs), each
 * checked to be a free, non-Unsplash+ photo whose recorded location matches the tour.
 * Weekdays follow Date#getUTCDay: 0 is Sunday, 6 is Saturday.
 */
'use strict';

const REPUBLIC_SQUARE = {
	url: 'https://maps.google.com/?q=Republic+Square+Yerevan',
	en: `Republic Square, Yerevan`,
	ru: `Площадь Республики, Ереван`,
	hy: `Հանրապետության հրապարակ, Երևան`,
};

const CASCADE = {
	url: 'https://maps.google.com/?q=Cascade+Complex+Yerevan',
	en: `Cascade Complex, at the foot of the stairs, Yerevan`,
	ru: `Каскад, у подножия лестницы, Ереван`,
	hy: `Կասկադ համալիր, աստիճանների ստորոտին, Երևան`,
};

const categories = [
	{ key: 'excursions', slug: 'excursions', names: { en: `Excursions`, ru: `Экскурсии`, hy: `Էքսկուրսիաներ` } },
	{ key: 'hiking', slug: 'hiking', names: { en: `Hiking`, ru: `Походы`, hy: `Արշավներ` } },
	{
		key: 'gastronomy',
		slug: 'gastronomy',
		names: { en: `Gastronomy & Tastings`, ru: `Гастрономия и дегустации`, hy: `Գաստրոնոմիա և համտեսներ` },
	},
];

const tours = [
	{
		key: 'tatev',
		category: 'excursions',
		price: 32000,
		duration: 720,
		difficulty: 'EASY',
		maxParticipants: 30,
		schedule: { weekdays: [6], time: '07:30', weeks: 8 },
		locationUrl: 'https://maps.google.com/?q=Tatev+Monastery',
		meetingLocationUrl: REPUBLIC_SQUARE.url,
		photos: [
			{ id: 'photo-1672924986550-eea7b31eb414', author: 'Evgeny Matveev' },
			{ id: 'photo-1634829842509-4c7612dce391', author: 'Narek Hakobyan' },
			{ id: 'photo-1778221558984-b42ed821b55c', author: 'Ash Shvoyan' },
		],
		translations: {
			ru: {
				title: `Татев и канатная дорога «Крылья Татева»`,
				description: `Однодневная поездка на юг Армении к монастырю Татев IX века, стоящему на краю ущелья реки Воротан. К монастырю поднимемся по «Крыльям Татева» — одной из самых длинных пассажирских канатных дорог в мире протяжённостью 5,7 км. По пути остановимся на смотровых площадках, а на обратном пути заедем к Чёртову мосту с природными источниками. Билет на канатную дорогу оплачивается отдельно.`,
				location: `Монастырь Татев, Сюникская область`,
				meetingLocation: REPUBLIC_SQUARE.ru,
				whatsIncluded: [`Трансфер на комфортабельном автобусе`, `Сопровождение гида`, `Вода в дороге`],
			},
			en: {
				title: `Tatev Monastery and the Wings of Tatev Ropeway`,
				description: `A full-day trip to southern Armenia and the 9th-century Tatev Monastery on the edge of the Vorotan gorge. We ride up on the Wings of Tatev, one of the longest passenger ropeways in the world at 5.7 km, stop at viewpoints along the way and visit Devil's Bridge with its natural springs on the way back. The ropeway ticket is paid separately.`,
				location: `Tatev Monastery, Syunik Province`,
				meetingLocation: REPUBLIC_SQUARE.en,
				whatsIncluded: [`Comfortable coach transfer`, `Guide`, `Bottled water`],
			},
			hy: {
				title: `Տաթևի վանք և «Տաթևի թևեր» ճոպանուղի`,
				description: `Մեկօրյա ուղևորություն դեպի Հայաստանի հարավ՝ Որոտանի կիրճի եզրին կանգնած IX դարի Տաթևի վանք։ Վանք կբարձրանանք «Տաթևի թևեր» ճոպանուղով՝ աշխարհի ամենաերկար ուղևորային ճոպանուղիներից մեկով, որի երկարությունը 5,7 կմ է։ Ճանապարհին կկանգնենք դիտակետերում, իսկ վերադարձին կայցելենք Սատանի կամուրջ՝ իր բնական աղբյուրներով։ Ճոպանուղու տոմսը վճարվում է առանձին։`,
				location: `Տաթևի վանք, Սյունիքի մարզ`,
				meetingLocation: REPUBLIC_SQUARE.hy,
				whatsIncluded: [`Հարմարավետ ավտոբուսով տեղափոխում`, `Էքսկուրսավար`, `Խմելու ջուր`],
			},
		},
	},
	{
		key: 'sevan',
		category: 'excursions',
		price: 12000,
		duration: 360,
		difficulty: 'EASY',
		maxParticipants: 40,
		schedule: { weekdays: [0], time: '10:00', weeks: 8 },
		locationUrl: 'https://maps.google.com/?q=Sevanavank',
		meetingLocationUrl: REPUBLIC_SQUARE.url,
		photos: [
			{ id: 'photo-1634726180955-e840f92fa473', author: 'Daria Kurennaya' },
			{ id: 'photo-1658417589725-23e89f6e493c', author: 'Mia' },
		],
		translations: {
			ru: {
				title: `Озеро Севан и монастырь Севанаванк`,
				description: `Полдня у самого большого озера Кавказа. Поднимемся по ступеням к монастырю Севанаванк IX века на полуострове — отсюда открывается лучший вид на озеро. Потом будет свободное время у воды и возможность попробовать местную рыбу в ресторане на берегу.`,
				location: `Севанаванк, Гегаркуникская область`,
				meetingLocation: REPUBLIC_SQUARE.ru,
				whatsIncluded: [`Трансфер`, `Сопровождение гида`, `Свободное время на берегу`],
			},
			en: {
				title: `Lake Sevan and Sevanavank Monastery`,
				description: `A half-day trip to the largest lake in the Caucasus. We climb the steps to the 9th-century Sevanavank Monastery on the peninsula, the best viewpoint over the lake, then have free time by the water and a chance to try local fish at a lakeside restaurant.`,
				location: `Sevanavank, Gegharkunik Province`,
				meetingLocation: REPUBLIC_SQUARE.en,
				whatsIncluded: [`Transfer`, `Guide`, `Free time on the shore`],
			},
			hy: {
				title: `Սևանա լիճ և Սևանավանք`,
				description: `Կեսօրյա ուղևորություն դեպի Կովկասի ամենամեծ լիճը։ Աստիճաններով կբարձրանանք թերակղզու վրա գտնվող IX դարի Սևանավանք, որտեղից բացվում է լճի լավագույն տեսարանը։ Այնուհետև ազատ ժամանակ կլինի ջրի մոտ և հնարավորություն՝ ափամերձ ռեստորանում համտեսելու տեղական ձուկ։`,
				location: `Սևանավանք, Գեղարքունիքի մարզ`,
				meetingLocation: REPUBLIC_SQUARE.hy,
				whatsIncluded: [`Տեղափոխում`, `Էքսկուրսավար`, `Ազատ ժամանակ ափին`],
			},
		},
	},
	{
		key: 'khor-virap-noravank',
		category: 'excursions',
		price: 20000,
		duration: 540,
		difficulty: 'EASY',
		maxParticipants: 30,
		schedule: { weekdays: [6], time: '09:00', weeks: 8 },
		locationUrl: 'https://maps.google.com/?q=Noravank+Monastery',
		meetingLocationUrl: REPUBLIC_SQUARE.url,
		photos: [
			{ id: 'photo-1677864109159-34eb97228c65', author: 'SnapSaga' },
			{ id: 'photo-1788013121708-3d2601e9667c', author: 'Hasmik Ghazaryan Olson' },
			{ id: 'photo-1675181736839-37dfe1715ade', author: 'Valeria V' },
			{ id: 'photo-1788013121618-52d78b370f31', author: 'Hasmik Ghazaryan Olson' },
		],
		translations: {
			ru: {
				title: `Хор Вирап и Нораванк`,
				description: `Два самых узнаваемых монастыря Армении за один день. Утром — Хор Вирап у подножия Арарата: по преданию, он стоит над подземельем, где 13 лет провёл Григорий Просветитель, а вид на Арарат отсюда самый близкий. Затем через ущелье Амагу доедем до Нораванка XIII века — монастыря среди красных скал, известного резьбой мастера Момика.`,
				location: `Хор Вирап и Нораванк, Араратская и Вайоцдзорская области`,
				meetingLocation: REPUBLIC_SQUARE.ru,
				whatsIncluded: [`Трансфер`, `Сопровождение гида`, `Вода в дороге`],
			},
			en: {
				title: `Khor Virap and Noravank`,
				description: `Armenia's two most recognisable monasteries in one day. In the morning we visit Khor Virap at the foot of Mount Ararat, built according to tradition over the pit where Gregory the Illuminator was held for 13 years, with the closest view of Ararat. Then we drive through the Amaghu gorge to 13th-century Noravank, set among red cliffs and known for the carvings of master Momik.`,
				location: `Khor Virap and Noravank, Ararat and Vayots Dzor Provinces`,
				meetingLocation: REPUBLIC_SQUARE.en,
				whatsIncluded: [`Transfer`, `Guide`, `Bottled water`],
			},
			hy: {
				title: `Խոր Վիրապ և Նորավանք`,
				description: `Հայաստանի երկու ամենաճանաչելի վանքերը մեկ օրում։ Առավոտյան կայցելենք Արարատի ստորոտին գտնվող Խոր Վիրապ, որը, ըստ ավանդության, կառուցված է այն գբի վրա, որտեղ 13 տարի պահվել է Գրիգոր Լուսավորիչը, և որտեղից բացվում է Արարատի ամենամոտ տեսարանը։ Այնուհետև Ամաղուի կիրճով կհասնենք XIII դարի Նորավանք՝ կարմիր ժայռերի մեջ, որը հայտնի է Մոմիկ վարպետի քանդակներով։`,
				location: `Խոր Վիրապ և Նորավանք, Արարատի և Վայոց ձորի մարզեր`,
				meetingLocation: REPUBLIC_SQUARE.hy,
				whatsIncluded: [`Տեղափոխում`, `Էքսկուրսավար`, `Խմելու ջուր`],
			},
		},
	},
	{
		key: 'aragats',
		category: 'hiking',
		price: 22000,
		duration: 600,
		difficulty: 'MODERATE',
		maxParticipants: 16,
		// The summit season ends with the first snow, usually by mid-October.
		schedule: { weekdays: [6], time: '07:00', weeks: 4 },
		locationUrl: 'https://maps.google.com/?q=Lake+Kari+Aragats',
		meetingLocationUrl: REPUBLIC_SQUARE.url,
		photos: [
			{ id: 'photo-1757175573937-ce4b5cdf14ac', author: 'Gevorg Avetisyan' },
			{ id: 'photo-1757175574865-2fa3fe76e012', author: 'Gevorg Avetisyan' },
		],
		translations: {
			ru: {
				title: `Восхождение на южную вершину Арагаца`,
				description: `Подъём на южную вершину Арагаца (3879 м) — самую доступную из четырёх вершин высочайшей горы Армении. Старт от озера Кари на высоте 3200 м, набор высоты около 700 метров по каменистой тропе. С вершины видны кратер вулкана, Арарат и полстраны. Нужны базовая физическая форма, треккинговая обувь и тёплая одежда: даже в сентябре на вершине холодно и ветрено.`,
				location: `Гора Арагац, Арагацотнская область`,
				meetingLocation: REPUBLIC_SQUARE.ru,
				whatsIncluded: [`Трансфер до озера Кари`, `Горный гид`, `Аптечка первой помощи`],
			},
			en: {
				title: `South Summit of Mount Aragats`,
				description: `A climb to the south summit of Aragats (3,879 m), the most accessible of the four peaks of Armenia's highest mountain. We start from Lake Kari at 3,200 m and gain about 700 m on a rocky trail. From the top you can see the volcano's crater, Ararat and half the country. Basic fitness, hiking boots and warm layers are required: even in September the summit is cold and windy.`,
				location: `Mount Aragats, Aragatsotn Province`,
				meetingLocation: REPUBLIC_SQUARE.en,
				whatsIncluded: [`Transfer to Lake Kari`, `Mountain guide`, `First-aid kit`],
			},
			hy: {
				title: `Արագածի հարավային գագաթի վերելք`,
				description: `Վերելք դեպի Արագածի հարավային գագաթ (3879 մ)՝ Հայաստանի ամենաբարձր լեռան չորս գագաթներից ամենահասանելին։ Մեկնարկը Քարի լճից է՝ 3200 մ բարձրությունից, և քարքարոտ արահետով կբարձրանանք մոտ 700 մետր։ Գագաթից երևում են հրաբխի խառնարանը, Արարատը և երկրի կեսը։ Անհրաժեշտ են նվազագույն ֆիզիկական պատրաստվածություն, արշավային կոշիկներ և տաք հագուստ․ նույնիսկ սեպտեմբերին գագաթին ցուրտ է և քամոտ։`,
				location: `Արագած լեռ, Արագածոտնի մարզ`,
				meetingLocation: REPUBLIC_SQUARE.hy,
				whatsIncluded: [`Տեղափոխում մինչև Քարի լիճ`, `Լեռնային ուղեկցորդ`, `Առաջին օգնության դեղատուփ`],
			},
		},
	},
	{
		key: 'gyumri',
		category: 'excursions',
		price: 18000,
		duration: 600,
		difficulty: 'EASY',
		maxParticipants: 30,
		schedule: { weekdays: [0], time: '09:00', weeks: 8 },
		locationUrl: 'https://maps.google.com/?q=Vardanants+Square+Gyumri',
		meetingLocationUrl: REPUBLIC_SQUARE.url,
		photos: [
			{ id: 'photo-1661244415506-988de2bf6657', author: 'Gor Davtyan' },
			{ id: 'photo-1624429864426-6630a4f766c9', author: 'Robert Levonyan' },
		],
		translations: {
			ru: {
				title: `Гюмри — город мастеров`,
				description: `Второй по величине город Армении с особой атмосферой: чёрный туф, кованые балконы и дома XIX века в районе Кумайри. Прогуляемся по старому центру, зайдём в церковь Семи ран и храм Спасителя, увидим Железный фонтан на площади Вардананц и заглянем в мастерскую местного ремесленника. Гюмри славится юмором, и гид знает лучшие городские истории.`,
				location: `Гюмри, Ширакская область`,
				meetingLocation: REPUBLIC_SQUARE.ru,
				whatsIncluded: [`Трансфер`, `Сопровождение гида`, `Посещение мастерской`],
			},
			en: {
				title: `Gyumri, the City of Craftsmen`,
				description: `Armenia's second-largest city has an atmosphere of its own: black tuff, wrought-iron balconies and 19th-century houses in the Kumayri district. We walk the old centre, visit the Church of the Seven Wounds and the Holy Saviour's Church, see the Iron Fountain on Vardanants Square and drop into a local craftsman's workshop. Gyumri is famous for its humour, and the guide knows the best local stories.`,
				location: `Gyumri, Shirak Province`,
				meetingLocation: REPUBLIC_SQUARE.en,
				whatsIncluded: [`Transfer`, `Guide`, `Workshop visit`],
			},
			hy: {
				title: `Գյումրի՝ վարպետների քաղաք`,
				description: `Հայաստանի երկրորդ խոշոր քաղաքը յուրահատուկ մթնոլորտ ունի՝ սև տուֆ, կռածո պատշգամբներ և XIX դարի տներ Կումայրի թաղամասում։ Կզբոսնենք հին կենտրոնում, կայցելենք Յոթ վերք և Ամենափրկիչ եկեղեցիներ, կտեսնենք Վարդանանց հրապարակի երկաթե շատրվանը և կմտնենք տեղի արհեստավորի արհեստանոց։ Գյումրին հայտնի է իր հումորով, և էքսկուրսավարը գիտի քաղաքի լավագույն պատմությունները։`,
				location: `Գյումրի, Շիրակի մարզ`,
				meetingLocation: REPUBLIC_SQUARE.hy,
				whatsIncluded: [`Տեղափոխում`, `Էքսկուրսավար`, `Այց արհեստանոց`],
			},
		},
	},
	{
		key: 'amberd',
		category: 'excursions',
		price: 14000,
		duration: 360,
		difficulty: 'EASY',
		maxParticipants: 25,
		// The road up to 2,300 m closes with the snow.
		schedule: { weekdays: [3], time: '10:00', weeks: 6 },
		locationUrl: 'https://maps.google.com/?q=Amberd+Fortress',
		meetingLocationUrl: REPUBLIC_SQUARE.url,
		photos: [
			{ id: 'photo-1667741836853-0fafbd23f5e7', author: 'Catherine Zaidova' },
			{ id: 'photo-1634138666283-a61fe12798cc', author: 'Narek Hakobyan' },
		],
		translations: {
			ru: {
				title: `Крепость Амберд на склоне Арагаца`,
				description: `Средневековая крепость Амберд стоит на высоте 2300 метров над слиянием двух горных рек. Осмотрим стены цитадели, церковь Вахрамашен XI века и княжескую баню, а на обратном пути заедем к монастырю Сагмосаванк над ущельем Касаха и к памятнику армянскому алфавиту у подножия Арагаца.`,
				location: `Амберд, Арагацотнская область`,
				meetingLocation: REPUBLIC_SQUARE.ru,
				whatsIncluded: [`Трансфер`, `Сопровождение гида`, `Вода в дороге`],
			},
			en: {
				title: `Amberd Fortress on the Slopes of Aragats`,
				description: `The medieval fortress of Amberd stands at 2,300 m above the meeting of two mountain rivers. We explore the citadel walls, the 11th-century Vahramashen Church and the princely bathhouse, then stop on the way back at Saghmosavank Monastery above the Kasakh gorge and at the Armenian Alphabet Monument at the foot of Aragats.`,
				location: `Amberd, Aragatsotn Province`,
				meetingLocation: REPUBLIC_SQUARE.en,
				whatsIncluded: [`Transfer`, `Guide`, `Bottled water`],
			},
			hy: {
				title: `Ամբերդ ամրոց Արագածի լանջին`,
				description: `Միջնադարյան Ամբերդ ամրոցը կանգնած է 2300 մետր բարձրության վրա՝ երկու լեռնային գետերի միախառնման վայրում։ Կզննենք միջնաբերդի պարիսպները, XI դարի Վահրամաշեն եկեղեցին և իշխանական բաղնիքը, իսկ վերադարձին կայցելենք Քասաղի կիրճի վերևում գտնվող Սաղմոսավանք և Արագածի ստորոտին գտնվող Հայոց այբուբենի հուշարձան։`,
				location: `Ամբերդ, Արագածոտնի մարզ`,
				meetingLocation: REPUBLIC_SQUARE.hy,
				whatsIncluded: [`Տեղափոխում`, `Էքսկուրսավար`, `Խմելու ջուր`],
			},
		},
	},
	{
		key: 'lastiver',
		category: 'hiking',
		price: 16000,
		duration: 540,
		difficulty: 'MODERATE',
		maxParticipants: 18,
		schedule: { weekdays: [6], time: '08:30', weeks: 6 },
		locationUrl: 'https://maps.google.com/?q=Lastiver+Yenokavan',
		meetingLocationUrl: REPUBLIC_SQUARE.url,
		photos: [{ id: 'photo-1545750214-7685c8e77df5', author: 'Vruyr Martirosyan' }],
		translations: {
			ru: {
				title: `Ластивер: лесная тропа к пещерам и водопаду`,
				description: `Поход по лесному ущелью в Тавушской области. Из села Енокаван спустимся к Ластиверу — месту с пещерами, домиками на деревьях и небольшим водопадом. Маршрут около 10 км со спусками и подъёмами, тропа местами крутая и после дождя скользкая, поэтому нужны удобная обувь и перекус.`,
				location: `Ластивер, Енокаван, Тавушская область`,
				meetingLocation: REPUBLIC_SQUARE.ru,
				whatsIncluded: [`Трансфер`, `Гид-проводник`, `Перекус на привале`],
			},
			en: {
				title: `Lastiver: Forest Trail to the Caves and Waterfall`,
				description: `A hike through a forested gorge in Tavush Province. From the village of Yenokavan we descend to Lastiver, with its caves, treehouses and a small waterfall. The route is about 10 km of ups and downs; the trail is steep in places and slippery after rain, so bring comfortable shoes and a snack.`,
				location: `Lastiver, Yenokavan, Tavush Province`,
				meetingLocation: REPUBLIC_SQUARE.en,
				whatsIncluded: [`Transfer`, `Hiking guide`, `Snack at the rest stop`],
			},
			hy: {
				title: `Լաստիվեր՝ անտառային արահետ դեպի քարանձավներ և ջրվեժ`,
				description: `Արշավ Տավուշի մարզի անտառապատ կիրճով։ Ենոքավան գյուղից կիջնենք Լաստիվեր՝ իր քարանձավներով, ծառերի վրա կառուցված տնակներով և փոքրիկ ջրվեժով։ Երթուղին մոտ 10 կմ է՝ վայրէջքներով և վերելքներով․ արահետը տեղ-տեղ զառիթափ է և անձրևից հետո սայթաքուն, ուստի վերցրեք հարմար կոշիկներ և թեթև նախուտեստ։`,
				location: `Լաստիվեր, Ենոքավան, Տավուշի մարզ`,
				meetingLocation: REPUBLIC_SQUARE.hy,
				whatsIncluded: [`Տեղափոխում`, `Արշավի ուղեկցորդ`, `Նախուտեստ կանգառի ժամանակ`],
			},
		},
	},
	{
		key: 'dilijan-haghartsin',
		category: 'excursions',
		price: 15000,
		duration: 480,
		difficulty: 'EASY',
		maxParticipants: 30,
		schedule: { weekdays: [0], time: '09:30', weeks: 8 },
		locationUrl: 'https://maps.google.com/?q=Haghartsin+Monastery',
		meetingLocationUrl: REPUBLIC_SQUARE.url,
		photos: [
			{ id: 'photo-1653113222184-2eeaeee9b1cd', author: 'Tatevik' },
			{ id: 'photo-1654104596809-59dbfa506764', author: 'Ekaterina Krusanova' },
			{ id: 'photo-1633450077736-4195e1053002', author: 'Mohamad Hajizade' },
		],
		translations: {
			ru: {
				title: `Дилижан и монастырь Агарцин`,
				description: `Дилижан называют армянской Швейцарией за леса и горный воздух. Прогуляемся по отреставрированной улице Шарамбеян со старинными домами и мастерскими, а затем поднимемся в лес к монастырскому комплексу Агарцин X–XIII веков. На обратном пути сделаем короткую остановку у озера Парз.`,
				location: `Дилижан, Тавушская область`,
				meetingLocation: REPUBLIC_SQUARE.ru,
				whatsIncluded: [`Трансфер`, `Сопровождение гида`, `Вода в дороге`],
			},
			en: {
				title: `Dilijan and Haghartsin Monastery`,
				description: `Dilijan is known as Armenia's Switzerland for its forests and mountain air. We stroll along restored Sharambeyan Street with its old houses and workshops, then drive up into the forest to the 10th–13th-century Haghartsin Monastery. On the way back we make a short stop at Lake Parz.`,
				location: `Dilijan, Tavush Province`,
				meetingLocation: REPUBLIC_SQUARE.en,
				whatsIncluded: [`Transfer`, `Guide`, `Bottled water`],
			},
			hy: {
				title: `Դիլիջան և Հաղարծին վանք`,
				description: `Դիլիջանը անվանում են Հայաստանի Շվեյցարիա՝ իր անտառների և լեռնային օդի համար։ Կզբոսնենք վերականգնված Շարամբեյան փողոցով՝ իր հին տներով և արհեստանոցներով, իսկ հետո անտառով կբարձրանանք X–XIII դարերի Հաղարծին վանական համալիր։ Վերադարձին կարճ կանգառ կանենք Պարզ լճի մոտ։`,
				location: `Դիլիջան, Տավուշի մարզ`,
				meetingLocation: REPUBLIC_SQUARE.hy,
				whatsIncluded: [`Տեղափոխում`, `Էքսկուրսավար`, `Խմելու ջուր`],
			},
		},
	},
	{
		key: 'sanahin-haghpat',
		category: 'excursions',
		price: 17000,
		duration: 600,
		difficulty: 'EASY',
		maxParticipants: 25,
		schedule: { weekdays: [6], time: '09:00', weeks: 8 },
		locationUrl: 'https://maps.google.com/?q=Sanahin+Monastery',
		meetingLocationUrl: REPUBLIC_SQUARE.url,
		photos: [{ id: 'photo-1658768490489-e3a1989f5f44', author: 'Wandr Owl' }],
		translations: {
			ru: {
				title: `Санаин и Ахпат — монастыри Лори`,
				description: `Два средневековых монастыря на краю Дебедского ущелья, вместе внесённые в список Всемирного наследия ЮНЕСКО. В Санаине пройдём по сумрачным галереям и книгохранилищу X–XIII веков, в Ахпате увидим знаменитые хачкары и фрески. По пути — виды ущелья и остановка в Алаверди.`,
				location: `Санаин и Ахпат, Лорийская область`,
				meetingLocation: REPUBLIC_SQUARE.ru,
				whatsIncluded: [`Трансфер`, `Сопровождение гида`, `Вода в дороге`],
			},
			en: {
				title: `Sanahin and Haghpat, the Monasteries of Lori`,
				description: `Two medieval monasteries on the edge of the Debed Canyon, listed together as a UNESCO World Heritage Site. At Sanahin we walk through the dim galleries and the 10th–13th-century library; at Haghpat we see its famous khachkars and frescoes. Along the way there are canyon views and a stop in Alaverdi.`,
				location: `Sanahin and Haghpat, Lori Province`,
				meetingLocation: REPUBLIC_SQUARE.en,
				whatsIncluded: [`Transfer`, `Guide`, `Bottled water`],
			},
			hy: {
				title: `Սանահին և Հաղպատ՝ Լոռու վանքերը`,
				description: `Դեբեդի կիրճի եզրին գտնվող երկու միջնադարյան վանքեր, որոնք միասին ընդգրկված են ՅՈՒՆԵՍԿՕ-ի Համաշխարհային ժառանգության ցանկում։ Սանահինում կանցնենք կիսամութ սրահներով և X–XIII դարերի գրատնով, իսկ Հաղպատում կտեսնենք նրա հայտնի խաչքարերը և որմնանկարները։ Ճանապարհին՝ կիրճի տեսարաններ և կանգառ Ալավերդիում։`,
				location: `Սանահին և Հաղպատ, Լոռու մարզ`,
				meetingLocation: REPUBLIC_SQUARE.hy,
				whatsIncluded: [`Տեղափոխում`, `Էքսկուրսավար`, `Խմելու ջուր`],
			},
		},
	},
	{
		key: 'brandy-tasting',
		category: 'gastronomy',
		price: 9000,
		duration: 120,
		difficulty: null,
		maxParticipants: 20,
		schedule: { weekdays: [5], time: '18:00', weeks: 8 },
		locationUrl: CASCADE.url,
		meetingLocationUrl: CASCADE.url,
		photos: [{ id: 'photo-1609933493187-3866f3cfab28', author: 'Gor Davtyan' }],
		translations: {
			ru: {
				title: `Дегустация армянского коньяка`,
				description: `Вечер для тех, кто хочет разобраться в армянском коньяке. Сомелье расскажет, как виноград Араратской долины становится коньячным спиртом, чем отличаются выдержки и почему в Армении коньяк пьют без льда. В программе — дегустация пяти коньяков разной выдержки с закусками. Только для гостей старше 18 лет.`,
				location: `Ереван, дегустационный зал`,
				meetingLocation: CASCADE.ru,
				whatsIncluded: [`Дегустация пяти коньяков`, `Закуски`, `Рассказ сомелье`],
			},
			en: {
				title: `Armenian Brandy Tasting`,
				description: `An evening for anyone curious about Armenian brandy. A sommelier explains how grapes from the Ararat Valley become brandy spirit, how the ageing categories differ and why brandy is drunk without ice in Armenia. The programme includes a tasting of five brandies of different ages with snacks. Guests must be 18 or older.`,
				location: `Yerevan, tasting room`,
				meetingLocation: CASCADE.en,
				whatsIncluded: [`Tasting of five brandies`, `Snacks`, `Sommelier's talk`],
			},
			hy: {
				title: `Հայկական կոնյակի համտես`,
				description: `Երեկո նրանց համար, ովքեր ցանկանում են ճանաչել հայկական կոնյակը։ Սոմելիեն կպատմի, թե ինչպես է Արարատյան դաշտի խաղողը վերածվում կոնյակի սպիրտի, ինչով են տարբերվում հնեցման տարիները և ինչու են Հայաստանում կոնյակը խմում առանց սառույցի։ Ծրագրում՝ տարբեր հնեցման հինգ կոնյակի համտես՝ նախուտեստներով։ Միայն 18 տարեկանից բարձր հյուրերի համար։`,
				location: `Երևան, համտեսի սրահ`,
				meetingLocation: CASCADE.hy,
				whatsIncluded: [`Հինգ կոնյակի համտես`, `Նախուտեստներ`, `Սոմելիեի պատմություն`],
			},
		},
	},
	{
		key: 'tolma-class',
		category: 'gastronomy',
		price: 14000,
		duration: 180,
		difficulty: null,
		maxParticipants: 12,
		schedule: { weekdays: [4], time: '17:00', weeks: 8 },
		locationUrl: CASCADE.url,
		meetingLocationUrl: CASCADE.url,
		photos: [
			{ id: 'photo-1759679134771-835a874351fe', author: 'Nellie Adamyan' },
			{ id: 'photo-1526016650454-68a6f488910a', author: 'Gor Davtyan' },
		],
		translations: {
			ru: {
				title: `Мастер-класс армянской кухни: толма и лаваш`,
				description: `Готовим вместе с хозяйкой, которая знает армянскую домашнюю кухню. Научимся заворачивать толму в виноградные листья, узнаем, чем летняя толма отличается от зимней, и посмотрим, как пекут лаваш. В конце — общий ужин из приготовленного, домашних солений и травяного чая. Все продукты и фартуки предоставляются.`,
				location: `Ереван, кулинарная студия`,
				meetingLocation: CASCADE.ru,
				whatsIncluded: [`Все продукты`, `Фартук и рецепты`, `Ужин из приготовленных блюд`],
			},
			en: {
				title: `Armenian Cooking Class: Tolma and Lavash`,
				description: `Cook with a host who knows Armenian home cooking. You'll learn to roll tolma in grape leaves, hear how summer tolma differs from the winter kind and watch lavash being baked. The class ends with a shared dinner of what you made, homemade pickles and herbal tea. All ingredients and aprons are provided.`,
				location: `Yerevan, cooking studio`,
				meetingLocation: CASCADE.en,
				whatsIncluded: [`All ingredients`, `Apron and recipes`, `Dinner of the dishes you cook`],
			},
			hy: {
				title: `Հայկական խոհանոցի վարպետաց դաս՝ տոլմա և լավաշ`,
				description: `Պատրաստում ենք հայկական տնային խոհանոցը լավ ճանաչող տանտիրուհու հետ։ Կսովորենք խաղողի տերևով տոլմա փաթաթել, կիմանանք, թե ինչով է ամառային տոլման տարբերվում ձմեռայինից, և կտեսնենք, թե ինչպես են լավաշ թխում։ Վերջում՝ ընդհանուր ընթրիք պատրաստածից, տնական թթուներով և խոտաբույսերի թեյով։ Բոլոր մթերքները և գոգնոցները տրամադրվում են։`,
				location: `Երևան, խոհարարական ստուդիա`,
				meetingLocation: CASCADE.hy,
				whatsIncluded: [`Բոլոր մթերքները`, `Գոգնոց և բաղադրատոմսեր`, `Ընթրիք պատրաստած ուտեստներից`],
			},
		},
	},
];

module.exports = { categories, tours };
